### ISSUE TITLE
Theme variant for vaadin-tabs with anchor and icon

### ISSUE THREAD

**Issue by niiyeboah** [vaadin/vaadin-tabs#129]
### Description
Currently when using `<vaadin-tabs>` for the drawer slot in `<vaadin-app-layout>` like the following code snippet:

```html
<vaadin-app-layout primary-section="drawer">

  ...

  <vaadin-tabs slot="drawer" orientation="vertical" selected="{{selected}}">
    <vaadin-tab>
      <a href="/employee-list">
        <iron-icon icon="vaadin:list"></iron-icon>
        <span>Employee list</span>
      </a>
    </vaadin-tab>
    <vaadin-tab>
      <a href="/employee-new">
        <iron-icon icon="vaadin:user-card"></iron-icon>
        <span>New employee</span>
      </a>
    </vaadin-tab>
  </vaadin-tabs>

  ...

</vaadin-app-layout>
```

You need to write some additional styles to make the menu tabs look good and align the icons. It would be nice if there was a **theme variant** for this use case. This could provide some default styling for `<vaadin-tabs>` that contain anchor tags and icons and would be particularly useful with `<vaadin-app-layout>` or in general when using `<vaadin-tabs>` for page navigation.

### Expected outcome
![Screenshot 2019-05-21 at 15 26 02](https://user-images.githubusercontent.com/3392815/58097278-b10f3c80-7bdf-11e9-81b8-ab8fbbe51471.png)

This screenshot is after applying the following CSS:

```css
vaadin-tabs a {
  justify-content: left;
}
vaadin-tabs a:hover {
  text-decoration: none;
}
vaadin-tab[selected] {
  background-color: var(--lumo-contrast-10pct);
}
vaadin-tabs a iron-icon {
  padding: 0.25em;
  padding-right: var(--lumo-space-m);
  width: var(--lumo-icon-size-s);
  height: var(--lumo-icon-size-s);
}
```

### Actual outcome
![Screenshot 2019-05-21 at 15 30 01](https://user-images.githubusercontent.com/3392815/58096436-b8cde180-7bdd-11e9-87c4-1f7feddbfe46.png)
